FROM node:20-alpine

WORKDIR /app

# Copiamos los archivos de dependencias
COPY package*.json ./

# Instalamos las dependencias dentro del contenedor
RUN npm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto de desarrollo de Angular
EXPOSE 4200

# Arrancamos Angular indicando que escuche en todas las interfaces (0.0.0.0) 
# Esto es obligatorio en Docker para que puedas acceder desde tu navegador en Windows
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll=2000"]