server {
    listen 80;
    server_name localhost;

    # Directorio donde están los archivos compilados
    root /usr/share/nginx/html;
    index index.html;

    # Compresión GZIP para que tu web cargue muchísimo más rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Magia para SPAs: Si el archivo o carpeta no existe, redirige a index.html
        try_files $uri $uri/ /index.html;
    }

    # Caché estática para imágenes y fuentes (Optimización de DevOps)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}