name: Deploy Frontend

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: rednorte-frontend

jobs:
  build-push-deploy:
    name: Build, Push & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versión estable y recomendada para Angular
          cache: 'npm'

      - name: 3. Instalar dependencias y Compilar
        run: |
          npm install
          npm run build

      - name: 4. Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 5. Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 6. Construir y Subir imagen Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: 7. Conectar al Clúster EKS
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: 8. Desplegar en Kubernetes
        run: |
          # Aplica el Deployment, el LoadBalancer y el HPA del frontend
          kubectl apply -f k8s/
          # Fuerza la descarga de la nueva imagen
          kubectl rollout restart deployment rednorte-frontend -n rednorte
